-- vim.cmd[[highpight Pmenu ctermbg=black guibg=black]]
--// vim.g.material_style = "deep ocean"

return {
    "rktjmp/lush.nvim",
    "folke/tokyonight.nvim",
    "rebelot/kanagawa.nvim",
    "marko-cerovac/material.nvim",
    "EdenEast/nightfox.nvim",
    "yorumicolors/yorumi.nvim",
    "scottmckendry/cyberdream.nvim",
    "sainnhe/gruvbox-material",
    "aktersnurra/no-clown-fiesta.nvim",
    "datsfilipe/vesper.nvim",
    "rafi/awesome-vim-colorschemes",
    "zenbones-theme/zenbones.nvim",
    "Yagua/nebulous.nvim",
    "ramojus/mellifluous.nvim",
    "metalelf0/jellybeans-nvim",
    "Verf/deepwhite.nvim",
    "kdheepak/monochrome.nvim",
    "vague2k/vague.nvim",
    "lunarvim/horizon.nvim",
    "andersevenrud/nordic.nvim",
    "oxfist/night-owl.nvim",
    "everviolet/nvim",
    --"0xstepit/flow.nvim",
    "slugbyte/lackluster.nvim",
    "zootedb0t/citruszest.nvim",
    "e-ink-colorscheme/e-ink.nvim",
    "luisiacc/gruvbox-baby",
    "ellisonleao/gruvbox.nvim",
    "catppuccin/nvim", name = "catppuccin", priority = 1000,
    "rose-pine/neovim",
    "rktjmp/lush.nvim",
    "nyoom-engineering/oxocarbon.nvim",
    "bluz71/vim-moonfly-colors",
    "bluz71/vim-nightfly-colors",
    "jacoborus/tender.vim",
    "savq/melange-nvim",
    "rmehri01/onenord.nvim",
    "everviolet/nvim",
    "olivercederborg/poimandres.nvim",
    "xero/miasma.nvim",
    "dgox16/oldworld.nvim",
    "ficd0/ashen.nvim",
    "water-sucks/darkrose.nvim",
}
